on:
  schedule:
  - cron: '0 * * * *'
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: Ash258/Scoop-GithubActions@stable-win
      env:
        GITH_EMAIL: 26007713+2EXP@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHOVEL: '1'
        SCOOP_BRANCH: 'NEW'
        SKIP_UPDATED: '1'
